<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Country::insert([
                ['name' => 'Afghanistan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Albania', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Algeria', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Andorra', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Angola', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Antigua and Barbuda', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Argentina', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Armenia', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Australia', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Austria', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Azerbaijan', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Bahamas', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Bahrain', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Bangladesh', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Barbados', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Belarus', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Belgium', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Belize', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Benin', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Bhutan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Bolivia', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Bosnia and Herzegovina', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Botswana', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Brazil', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Brunei', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Bulgaria', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Burkina Faso', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Burundi', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Cabo Verde', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Cambodia', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Cameroon', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Canada', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Central African Republic', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Chad', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Chile', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'China', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Colombia', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Comoros', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Congo (Congo-Brazzaville)', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Costa Rica', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Croatia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Cuba', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Cyprus', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Czechia (Czech Republic)', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Democratic Republic of the Congo', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Denmark', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Djibouti', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Dominica', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Dominican Republic', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Ecuador', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Egypt', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'El Salvador', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Equatorial Guinea', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Eritrea', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Estonia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Eswatini (fmr. "Swaziland")', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Ethiopia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Fiji', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Finland', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'France', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Gabon', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Gambia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Georgia', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Germany', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Ghana', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Greece', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Grenada', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Guatemala', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Guinea', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Guinea-Bissau', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Guyana', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Haiti', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Holy See', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Honduras', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Hungary', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Iceland', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'India', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Indonesia', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Iran', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Iraq', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Ireland', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Israel', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Italy', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Jamaica', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Japan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Jordan', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Kazakhstan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Kenya', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Kiribati', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Kuwait', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Kyrgyzstan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Laos', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Latvia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Lebanon', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Lesotho', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Liberia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Libya', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Liechtenstein', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Lithuania', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Luxembourg', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Madagascar', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Malawi', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Malaysia', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Maldives', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Mali', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Malta', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Marshall Islands', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Mauritania', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Mauritius', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Mexico', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Micronesia', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Moldova', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Monaco', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Mongolia', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Montenegro', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Morocco', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Mozambique', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Myanmar (Burma)', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Namibia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Nauru', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Nepal', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Netherlands', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'New Zealand', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Nicaragua', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Niger', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Nigeria', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'North Korea', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'North Macedonia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Norway', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Oman', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Pakistan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Palau', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Palestine State', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Panama', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Papua New Guinea', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Paraguay', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Peru', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Philippines', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Poland', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Portugal', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Qatar', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Romania', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Russia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Rwanda', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Saint Kitts and Nevis', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Saint Lucia', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Saint Vincent and the Grenadines', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Samoa', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'San Marino', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Sao Tome and Principe', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Saudi Arabia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Senegal', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Serbia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Seychelles', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Sierra Leone', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Singapore', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Slovakia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Slovenia', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Solomon Islands', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Somalia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'South Africa', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'South Korea', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'South Sudan', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Spain', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Sri Lanka', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Sudan', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Suriname', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Sweden', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Switzerland', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Syria', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Taiwan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Tajikistan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Tanzania', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Thailand', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Timor-Leste', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Togo', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Tonga', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Trinidad and Tobago', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Tunisia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Turkey', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Turkmenistan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Tuvalu', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Uganda', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Ukraine', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'United Arab Emirates', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'United Kingdom', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'United States of America', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Uruguay', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Uzbekistan', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Vanuatu', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Vatican City', 'region_id' => 2, 'created_at' => now()],
                ['name' => 'Venezuela', 'region_id' => 1, 'created_at' => now()],
                ['name' => 'Vietnam', 'region_id' => 4, 'created_at' => now()],
                ['name' => 'Yemen', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Zambia', 'region_id' => 3, 'created_at' => now()],
                ['name' => 'Zimbabwe', 'region_id' => 3, 'created_at' => now()]
            ]);
    }
}
